### ISSUE TITLE
[Compatibility] Acquisition enchant and Storage Drawers

### ISSUE THREAD

**Issue by CerbinTalYalas** [svenhjol/CharmForge#27] opened 2021-01-06 16:36 UTC
Versions
* Charm version - `2.2.0`
* Storage Drawers version - `8.2.1`
* Minecraft version - `1.6.4`

Description
When mining any drawer with an Acquisition tool, it actually duplicates the drawer : one is added to the inventory, but the drawer actually stays in place. Since the drawer works like a Shulker Box and content is sealed inside when destroyed, it's actually duplicating all its content too.  
Will report this bug too on StorageDrawers github, as I don't know which mod is causing this unexpected behaviour : https://github.com/jaquadro/StorageDrawers/issues/907.

**Comment by CerbinTalYalas** [comment] 2021-01-07 17:38
Just realised this issue is already opened here : https://github.com/svenhjol/CharmForge/issues/9
Dunno how to mark my issue as a duplicate, will leave it open in case someone comes here from Storage Drawers github

**Comment by F43nd1r** [comment] 2021-01-07 17:41
Duplicate of #9

**Closed by F43nd1r** 2021-01-07 17:41 UTC
