### ISSUE TITLE
Bug - Spawner doesn't break - charm-forge-1.16.4-2.2.2

### ISSUE THREAD

**Issue by martinsebik** [svenhjol/CharmForge#41] opened 2021-01-15 13:02 UTC
Breaking a spawner with a pickaxe which has the acquisition enchantment drops xp but doesn't break the spawner.
May be an incompatibility with Apotheosis?
Additionally - the anvil (also changed by apotheosis) disappears when mined with acquisition.

**Comment by F43nd1r** [comment] 2021-01-17 20:47
Duplicate of #3

**Closed by F43nd1r** 2021-01-17 20:47 UTC
