### ISSUE TITLE
idk help please 

### ISSUE THREAD

**Issue by mike17681** [svenhjol/CharmForge#30] opened 2021-01-08 03:28 UTC
Versions
* Charm version  `2.2.x`
* Minecraft version forge `1.6.4`

Description
it says tht there is a issue whit charm idk why im not a programer i just play minecraft for fun 

![image](https://user-images.githubusercontent.com/77135821/103971008-25894d00-512f-11eb-85e9-edfa599f0cf2.png)

![image](https://user-images.githubusercontent.com/77135821/103971040-3043e200-512f-11eb-9dab-d36c4d1ea2ff.png)

![image](https://user-images.githubusercontent.com/77135821/103971055-3639c300-512f-11eb-8a1c-93e067343bc6.png)

![image](https://user-images.githubusercontent.com/77135821/103971070-3d60d100-512f-11eb-8fd4-aaf0cf52e8dc.png)

**Comment by ridjack** [comment] 2021-01-08 15:10
Duplicate of #25. Update Quark, and use the Search feature in future.

**Closed by ridjack** 2021-01-08 15:10 UTC
