### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaBro123** [svenhjol/CharmForge#73] opened 2021-02-20 18:09 UTC
Read me first!
1. Is your issue about the Fabric version of Charm? Please report your issue here: https://github.com/svenhjol/Charm/issues
2. We don't support Optifine! Please check that the problem still occurs if you remove Optifine from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - 
![image](https://user-images.githubusercontent.com/51277766/108604485-21be2c80-7363-11eb-819a-3df0a4d9f021.png)
* Minecraft version - 1.16.5.

Description
The game crashes. No report is given.

Optional: Steps To Reproduce
Run the game.

Optional: Stacktrace/Screenshots
No report is given.
Logs file might help. Otherwise, I don't know.
https://pastebin.com/xsPu0CwT
![image](https://user-images.githubusercontent.com/51277766/108604531-55995200-7363-11eb-8f8c-27d250606a3f.png)

**Comment by NoDreamsRemain** [comment] 2021-02-22 21:01
it happens to me too
i have quark mod. Should it be the problem?

**Comment by F43nd1r** [comment] 2021-02-22 21:11
Duplicate of #66

**Closed by F43nd1r** 2021-02-22 21:11 UTC
