### ISSUE TITLE
DUPE BUG Acquisition Enchant

### ISSUE THREAD

**Issue by celsiusqc** [svenhjol/CharmForge#33] opened 2021-01-09 22:25 UTC
Read me first!
1. Is your issue about the Fabric version of Charm? Please report your issue here: https://github.com/svenhjol/Charm/issues
2. We don't support Optifine! Please check that the problem still occurs if you remove Optifine from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - 2.1.9
* Minecraft version - e.g. 1.16.4

Description
Acquisition enchant on a compacting drawer from Drawers mod will drop one in your inventory and keep the drawer in the world, essentially you could dupe items inside the drawer endlessly

Optional: Steps To Reproduce
This helps us to repeat the issue you're having.
add acquisition to a stone pickaxe, try and break a compacting drawer, boom it dupes it

Optional: Stacktrace/Screenshots
By adding a stacktrace (e.g. pastebin link) and/or screenshots it helps us understand and fix the problem.

**Comment by Coranthes** [comment] 2021-01-09 22:34
Duplicate of # 9

**Closed by Coranthes** 2021-01-09 22:34 UTC
