### ISSUE TITLE
Game crashes when launching without producing a crash report.

### ISSUE THREAD

**Issue by Smokedeuch** [svenhjol/CharmForge#74] opened 2021-02-20 18:16 UTC
Versions
* Charm version 2.2.2
* Minecraft version 1.16.5

Description
Game launches to forge compiling screen and then crashes after a few seconds

Aditional Note
Game launches fine after removing CharmReforged

Log File:

MultiMC version: 0.6.12-develop-1520

Minecraft folder is:
C:/Users/owner/Desktop/MultiMC/instances/Vanilla - Create/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_201, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/owner/Desktop/MultiMC/instances/Vanilla - Create/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/owner/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/owner/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/owner/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/owner/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/owner/Desktop/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.0.25/forge-1.16.5-36.0.25-launcher.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/owner/Desktop/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/owner/Desktop/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1/nashorn-core-compat-15.1.1.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/owner/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/owner/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] abnormals_core-1.16.4-3.0.6
  [✔️] addendum-1.16.5-1.2.3
  [✔️] Apotheosis-1.16.3-4.4.1
  [✔️] Artifacts-1.16.5-2.7.7
  [✔️] atmospheric-1.16.4-3.0.0
  [✔️] AutoRegLib-1.6-47
  [✔️] autumnity-1.16.4-2.0.1
  [✔️] baubley-heart-canisters-1.16.4-1.1.2
  [✔️] beaconsforall-forge-1.16.5-5.1.0.1
  [✔️] bedspreads-forge-1.16.4-5.1.0.1
  [✔️] berry_good-1.16.4-4.0.0
  [✔️] BetterAdvancements-1.16.4-0.1.0.104
  [✔️] Better-Badlands-1.16.5-2.0.3
  [✔️] BetterCaves-Forge-1.16.4-1.1.1
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.1
  [✔️] BetterPortals-1.16.4-0.2.1
  [✔️] BiomesOPlenty-1.16.4-13.0.0.431-universal
  [✔️] Bookshelf-1.16.5-10.0.1
  [✔️] Botania-1.16.4-411
  [✔️] Bountiful+Baubles+FORGE-1.16.3-0.0.2
  [✔️] Bountiful-1.16.4-3.3.0
  [✔️] buzzier_bees-1.16.4-3.0.0
  [✔️] byg-1.1.10
  [✔️] champions-forge-1.16.5-2.0.1.3
  [✔️] charm-forge-1.16.4-2.2.2
  [✔️] chocolate-1.3.0-1.16.4
  [✔️] citadel-1.6.1
  [✔️] comforts-forge-1.16.4-4.0.1.0
  [✔️] create-mc1.16.3_v0.3e
  [✔️] curios-forge-1.16.5-4.0.4.0
  [✔️] Cursed-1.16.5-7.0.1
  [✔️] DarkUtilities-1.16.5-8.0.3
  [✔️] DungeonCrawl-1.16.3-2.2.4
  [✔️] dungeons_mobs-1.16.4-1.0.3
  [✔️] dungeons_plus-1.16.4-1.1.3
  [✔️] DungeonsMod-1.16.3-1.1.18
  [✔️] EnchantmentDescriptions-1.16.5-7.0.3
  [✔️] enchantwithmob-1.16.4-2.3.3
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] EndRemastered-R352
  [✔️] enhancedcelestials-1.0.1-1.16.4
  [✔️] Enhanced-Mushrooms-1.16.4-3.0.3
  [✔️] extraboats-1.16.5-2.1.0
  [✔️] furniture-7.0.0-pre19-1.16.3
  [✔️] guardvillagers-1.16.4-1.1.9
  [✔️] hole_filler_mod_1.2.1_1.16.1-1.16.5
  [✔️] hunterillager-1.16.4-1.2.2
  [✔️] Hwyla-forge-1.10.11-B78_1.16.2
  [✔️] iceandfire-2.1.5-1.16.4
  [✔️] illagersweararmor-1.0.4
  [✔️] Inspirations-1.16.5-1.2.2
  [✔️] ironchest-1.16.4-11.2.10
  [✔️] ironfurnaces-1.16.5-2.6.3
  [✔️] jei-1.16.4-7.6.1.71
  [✔️] jei-professions-1.0.0-1.16.4
  [✔️] JustEnoughResources-1.16.4-0.12.0.104
  [✔️] Kiwi-1.16.3-3.4.1
  [✔️] kotlinforforge-1.9.0-obf
  [✔️] majrusz-library-1.16.4-1.3.0
  [✔️] majruszs-difficulty-1.16.4-0.5.1
  [✔️] Mantle-1.16.5-1.6.79
  [✔️] minecolonies-0.13.615-ALPHA-universal
  [✔️] neapolitan-1.16.4-2.0.1
  [✔️] Paraglider-1.16.2-1.3.1.0
  [✔️] Patchouli-1.16.4-50
  [✔️] Pillagers-1.16.5-3.0.1
  [✔️] Placebo-1.16.4-4.4.1
  [✔️] ProgressiveBosses-2.2.0-mc1.16.x
  [✔️] QuarkOddities-1.16.3
  [✔️] Quark-r2.4-304
  [✔️] relics-0.1.4
  [✔️] reliquary-1.16.3-1.3.4.1061
  [✔️] repurposed_structures-1.16.4-2.3.4
  [✔️] savageandravage-1.16.4-3.0.0
  [✔️] SereneSeasons-1.16.5-4.0.1.91-universal
  [✔️] simplytea-1.16.5-2.3.4
  [✔️] SnowRealMagic-1.16.4-2.3.2
  [✔️] SpawnerFix-1.16.2-1.0.0.2
  [✔️] spiders-2.0-1.16.4-1.0.4
  [✔️] structure_gel-1.16.4-1.7.5
  [✔️] structurize-0.13.113-ALPHA-universal
  [✔️] the-conjurer-1.16.4-1.0.13
  [✔️] towers_of_the_wild-1.16.4-2.0.1
  [✔️] tumbleweed-1.16-0.4.9
  [✔️] upgrade_aquatic-1.16.5-3.0.1
  [✔️] veinmining-forge-1.16.5-0.8
  [✔️] voyage-1.16.4-1.0.3
  [✔️] VTweaks-1.16.4-3.4.1.1
  [✔️] wonderful-enchantments-1.16.4-1.0.4
  [✔️] YungsApi-1.16.4-Forge-4

Params:
  --username  --version MultiMC5 --gameDir C:/Users/owner/Desktop/MultiMC/instances/Vanilla - Create/.minecraft --assetsDir C:/Users/owner/Desktop/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.0.25 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx5120m, -Duser.language=en]

Minecraft process ID: 2292

Using onesix launcher.

2021-02-20 12:05:26,226 main WARN Advanced terminal features are not available in this environment
[12:05:26] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, derpyderp5000, --version, MultiMC5, --gameDir, C:/Users/owner/Desktop/MultiMC/instances/Vanilla - Create/.minecraft, --assetsDir, C:/Users/owner/Desktop/MultiMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, legacy, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.0.25, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[12:05:26] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_201 by Oracle Corporation
[12:05:27] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[12:05:27] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/owner/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[12:05:32] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [tictim.paraglider.MixinConnector]
[12:05:32] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[12:05:32] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[12:05:32] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [corgiaoc.byg.mixin.MixinConnector]
[12:05:32] [main/INFO] [co.by.BYG/]: BYG: Mixin Connected!
[12:05:32] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, C:\Users\owner\Desktop\MultiMC\instances\Vanilla - Create\.minecraft, --assetsDir, C:\Users\owner\Desktop\MultiMC\assets, --uuid, <PROFILE ID>, --username, derpyderp5000, --assetIndex, 1.16, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 854, --height, 480]
[ApotheosisCore]: Patching LivingEntity#blockUsingShield
[ApotheosisCore]: Patching LivingEntity#applyPotionDamageCalculations
[ApotheosisCore]: Patching Item#getItemEnchantability
[Serene Seasons Transformer]: Transforming func_228438_a_ in net/minecraft/client/renderer/WorldRenderer
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_228436_a_ in net/minecraft/client/renderer/WorldRenderer
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_201854_a in net/minecraft/world/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming func_201850_b in net/minecraft/world/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[ApotheosisCore]: Patching EnchantmentHelper#getEnchantmentModifierDamage 
[ApotheosisCore]: Patching EnchantmentHelper#getModifierForCreature
[ApotheosisCore]: Patching EnchantmentHelper#applyThornEnchantments
[ApotheosisCore]: Patching EnchantmentHelper#applyArthropodEnchantments
[ApotheosisCore]: Patching buildEnchantmentList for the Enchantability affix.
[ApotheosisCore]: Patching EnchantmentHelper#getEnchantmentDatas
[ApotheosisCore]: Patching ItemStack#onItemUse
[ApotheosisCore]: Patching TemptGoal#isTempting
[ApotheosisCore]: Patching CrossbowItem#onItemRightClick
[ApotheosisCore]: Patching CrossbowItem#fireProjectile
[ApotheosisCore]: Patching Item#getItemEnchantability
[12:05:34] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Corridor is public in charm.mixins.json:MineshaftPiecesMixin and should be specified in value
[12:05:34] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Room is public in charm.mixins.json:MineshaftPiecesMixin and should be specified in value
[ApotheosisCore]: Patching RepairContainer#updateRepairOutput
[ApotheosisCore]: Successfully removed the anvil level cap.
[ApotheosisCore]: Replaced ContainerRepair Enchantment#getMaxLevel #1.
[ApotheosisCore]: Replaced ContainerRepair Enchantment#getMaxLevel #2.
[ApotheosisCore]: Patching AnvilScreen#drawGuiContainerForegroundLayer
[12:05:34] [main/INFO] [ne.mi.co.Co.placebo/COREMODLOG]: Patching ModelBakery#<init>
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
[12:05:34] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.reflect.InvocationTargetException
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:63)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 19 more
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method hookAttemptDataFixInternal(Lcom/mojang/datafixers/DSL$TypeReference;Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in charm.mixins.json:UtilMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap charm.mixins.refmap.json
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[12:05:34] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 30 more
[12:05:34] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1.
Clipboard copy at: 20 Feb 2021 12:09:49 -0600

**Comment by F43nd1r** [comment] 2021-02-22 21:10
Duplicate of #66

**Closed by F43nd1r** 2021-02-22 21:10 UTC
