### ISSUE TITLE
Bug With Portable Crafting And FastWorkbench

### ISSUE THREAD

**Issue by i-am-bad-at-names** [svenhjol/CharmForge#75] opened 2021-02-21 08:46 UTC
Versions
* Charm version - charm-forge-1.16.4-2.2.2
* Minecraft version - 1.16.5

Description
The knowledge book is visible in the survival inventory even though [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench) is removing it, clicking it does nothing though. 

Steps To Reproduce
* Install [Charm Reforged](https://www.curseforge.com/minecraft/mc-mods/charm-reforged) and [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
* Set [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench) to disable the knowledge book in it's config
* Load up a world(not tested in servers)
* Switch to survival
* Put a crafting table in your inventory

Screenshots

![How it's supposed to be](https://user-images.githubusercontent.com/79395686/108619947-7094c080-744e-11eb-8515-2e7e91ebfe5e.png)
How it is without a crafting table
![2021-02-21_13 25 24](https://user-images.githubusercontent.com/79395686/108619950-7ab6bf00-744e-11eb-98e9-7cbcd04b2f31.png)
How it is with a crafting table
![2021-02-21_13 25 28](https://user-images.githubusercontent.com/79395686/108619954-84402700-744e-11eb-936a-895039f88ba8.png)
No book in portable crafting gui though
![2021-02-21_13 25 39](https://user-images.githubusercontent.com/79395686/108619958-8b673500-744e-11eb-9000-30c98bc74064.png)
Throwing the table away while in inventory

**Comment by F43nd1r** [comment] 2021-02-23 00:07
Duplicate of #24

**Closed by F43nd1r** 2021-02-23 00:07 UTC
Labels: compatibility
