### ISSUE TITLE
Charm Mixins Json Error? Charm Forge 2.1.9

### ISSUE THREAD

**Issue by RainnMannx** [svenhjol/CharmForge#64] opened 2021-02-07 00:58 UTC
[main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Corridor is public in charm.mixins.json:MineshaftPiecesMixin and should be specified in value
[main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Room is public in charm.mixins.json:MineshaftPiecesMixin and should be specified in value

Maybe minor? OCD on the log warning =P

**Comment by F43nd1r** [comment] 2021-02-22 23:28
Duplicate of #42

**Closed by F43nd1r** 2021-02-22 23:28 UTC
